CREATE TABLESPACE TS_KEY
DATAFILE 'E://bdLabs//TS_KEY.dbf'
SIZE 7 m
autoextend on next 5 m
maxsize 20 m
extent management local;

CREATE TEMPORARY TABLESPACE TS_KEY_TEMP
TEMPFILE 'E://bdLabs//TS_KEY_TEMP.dbf'
SIZE 5 m
autoextend on next 3 m
maxsize 30 m
extent management local;

SELECT TABLESPACE_NAME, STATUS, contents logging FROM SYS.DBA_TABLESPACES
 
SELECT FILE_NAME, TABLESPACE_NAME, STATUS, MAXBYTES, USER_BYTES FROM DBA_DATA_FILES
UNION
SELECT FILE_NAME, TABLESPACE_NAME, STATUS, MAXBYTES, USER_BYTES FROM DBA_TEMP_FILES

CREATE ROLE C##RLKEYCORE;
SELECT * FROM dba_roles WHERE ROLE LIKE 'C##%';



GRANT CREATE SESSION,
CREATE TABLE,
CREATE VIEW,
CREATE PROCEDURE TO C##RLKEYCORE;

GRANT CREATE TABLESPACE STO C##RLKEYCORE
GRANT ALTER TABLESPACE TO C##RLKEYCORE 
GRANT INSERT ANY TABLE TO C##RLKEYCORE
GRANT INSERT ANY TABLE TO C##RLKEYCORE 
GRANT RESOURCE TO C##RLKEYCORE 

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE LIKE 'C##%';

CREATE PROFILE C##PF_KEYCORE LIMIT
PASSWORD_LIFE_TIME 180 
SESSIONS_PER_USER 3
FAILED_LOGIN_ATTEMPTS 7
PASSWORD_LOCK_TIME 1
PASSWORD_REUSE_TIME 10
PASSWORD_GRACE_TIME DEFAULT
CONNECT_TIME 180
IDLE_TIME 30

SELECT * FROM DBA_PROFILES WHERE PROFILE = 'C##PF_KEYCORE';
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'DEFAULT';
SELECT * FROM DBA_PROFILES;

CREATE USER C##KEY_CORE IDENTIFIED BY 12345
DEFAULT TABLESPACE TS_KEY QUOTA UNLIMITED ON TS_KEY
TEMPORARY TABLESPACE TS_KEY_TEMP
PROFILE C##PF_KEYCORE
ACCOUNT UNLOCK
PASSWORD EXPIRE

GRANT C##RLKEYCORE TO C##KEY_CORE